version: '3.8'
services:
  web:
    image: dockerlivenet-web:latest
    container_name: web-production
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
      #- .:/app
      #- node_modules:/app/node_modules
    ports:
      - 2080:80
    environment:
      #- NODE_ENV=production
      - PORT=80
      - HOST=localhost
      #- MONGO_URL=mongodb://mongo:27017
      #- MONGO_DB=dev
      #- MONGO_USER=dev
      #- MONGO_PASSWORD=dev
      #- JWT_SECRET=dev
      #- JWT_EXPIRES_IN=1d
      #- JWT_COOKIE_EXPIRES_IN=1
      #- EMAIL_HOST=localhost
    #networks:
    #  - dev
    #depends_on:
    #  - mongo
    #  - redis
